// <auto-generated />
using System;
using Fiap.Web.Alunos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.Alunos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Alunos.Models.AreaVerdeModel", b =>
                {
                    b.Property<int>("AreaVerdeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaVerdeId"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Tamanho")
                        .HasColumnType("NUMBER(9,2)");

                    b.HasKey("AreaVerdeId");

                    b.ToTable("AreaVerde", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.IrrigacaoInteligenteModel", b =>
                {
                    b.Property<int>("IrrigacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IrrigacaoId"));

                    b.Property<int>("AreaVerdeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("date");

                    b.HasKey("IrrigacaoId");

                    b.HasIndex("AreaVerdeId");

                    b.ToTable("IrrigacaoInteligente", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.LeituraSensorModel", b =>
                {
                    b.Property<int>("LeituraSensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeituraSensorId"));

                    b.Property<DateTime>("Horario")
                        .HasColumnType("date");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(9,2)");

                    b.HasKey("LeituraSensorId");

                    b.HasIndex("SensorId");

                    b.ToTable("LeituraSensor", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.SensorModel", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SensorId");

                    b.ToTable("Sensor", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.IrrigacaoInteligenteModel", b =>
                {
                    b.HasOne("Fiap.Web.Alunos.Models.AreaVerdeModel", "AreaVerde")
                        .WithMany()
                        .HasForeignKey("AreaVerdeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaVerde");
                });

            modelBuilder.Entity("Fiap.Web.Alunos.Models.LeituraSensorModel", b =>
                {
                    b.HasOne("Fiap.Web.Alunos.Models.SensorModel", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
